Change file structure and render test element to DOM
table-for-five/reviews pull request #2
Opened 2019-02-11 05:14 UTC by alletsz

Render test element to DOM

2019-02-11 18:53 UTC, lydiahu8 commented on Client/src/components/App.jsx
> +         < Overview />
There shouldn't be a space between < and Overview. It should be <Overview />

2019-02-11 18:54 UTC, lydiahu8 commented on Client/src/components/App.jsx
> +    constructor(props) {
I would suggest changing your VS code settings tabsize to 2 instead of 4. Some of your indentations are 4 spaces as opposed to 2.

2019-02-11 18:55 UTC, lydiahu8 commented on Client/src/components/App.jsx
> +class Overview extends React.Component {
I would suggest putting this Overview component on a different file for separation of concerns.

2019-02-11 18:56 UTC, lydiahu8 commented on Client/src/index.jsx
> +
You should get rid of one of these empty lines

2019-02-11 18:57 UTC, lydiahu8 commented on Client/src/index.jsx
> +
There should only be one extra line after the end of the last line of code in a file

2019-02-11 18:59 UTC, lydiahu8 commented on data.js
> +  restaurantArr.push(newRestaurant());
Did you forget to pass in the 'i' into the newRestaurant() function?

2019-02-11 19:05 UTC, lydiahu8 requested changes
Good job Stella! I left a couple comments on some of the files in terms of best practices and I'm going to list a couple suggestions here:
1) Add node_modules directory into .gitignore. This directory is created when someone npm installs on their local disk. You shouldn't need to stage, commit, or push this into your github. It will make your pull requests a lot cleaner.
2) Look into CSS modules vs Styled Components for css styling because using regular css may cause issues when we are all trying to put our components together later down the road. Styled Components and CSS modules will alleviate the stress of our classnames conflicting with each other and possibly overriding each other.

2019-02-11 23:02 UTC, gakittle reviewed
It looks like lines 42 to 57 in newRestaurant are indented by 4 spaces, make sure to set all that to 2. There's also some commented out old code at the start of data.js and end of index.js that I'd delete.

Nice use of reduce in taking the averages!

2019-02-12 05:52 UTC, gakittle approved these changes
Looks great!

2019-02-13 18:29 UTC, gakittle approved these changes
Nice clean up! A couple comments:

- Line 28 of Overview reads "Whats [x] People Are Saying", is that a typo?
- Are we worried about component collisions at all? As in, will your overview component have a problem working with Phil's components, which probably include something named Overview?
- The "webpack tweak" commit only includes the bundle.js file, which is still getting committed.

2019-02-14 01:02 UTC, merged